/** request token event type */
export const GOOGLE_DRIVE_AUTH_EVENT = 'GOOGLE_DRIVE_AUTH_EVENT'

export const GOOGLE_DRIVE_UPLOAD_EVENT = 'GOOGLE_DRIVE_UPLOAD_EVENT'

export const FS_MKDIR_EVENT = 'FS_MKDIR_EVENT'

export const FS_WRITE_FILE_EVENT = 'FS_WRITE_FILE_EVENT'

export const FS_RM_EVENT = 'FS_RM_EVENT'

export const FS_RMDIR_EVENT = 'FS_RMDIR_EVENT'
